### ISSUE TITLE
Allow other ways to separate words in controllers and end points

### ISSUE THREAD

**Issue by Gisleburt** [AyeAyeApi/Api#6]
Currently you separate words with a hyphen. Eg `getUserNameAction` would be `user-name`. However, not all systems use this as the way to separate words. For example, PHP's `urlencode()` function uses `+`. Browsers will use `%20`. 

This could be added to `Controller::parseActionName()`. This should be completed after #2 as it will add a parser for child controllers.

**Comment by AyeAyeApi** [comment]
Fixed by 43d2600dca6b17bffeec604ead2f04d4a59bd11a
